# Workflow-এর নাম
name: 'Enforce Blog-Only Changes'

# কখন এই Workflow চলবে?
# এটি প্রতিটি পুল রিকোয়েস্ট তৈরি বা আপডেট হওয়ার সময় চলবে
on:
  pull_request:
    branches:
      - main

jobs:
  check-changed-files:
    runs-on: ubuntu-latest
    steps:
      # ধাপ ১: কোডটি চেকআউট করা
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # সম্পূর্ণ git history লোড করার জন্য

      # ধাপ ২: শুধুমাত্র পরিবর্তিত ফাইলগুলোর তালিকা বের করা
      - name: Get changed files
        id: changed-files
        run: |
          # বেস ব্রাঞ্চ (main) এবং বর্তমান ব্রাঞ্চের মধ্যে পরিবর্তিত ফাইলগুলোর তালিকা বের করা হচ্ছে
          FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          echo "changed_files<<EOF" >> $GITHUB_OUTPUT
          echo "$FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      # ধাপ ৩: ফাইলগুলো অনুমোদিত ফোল্ডারে আছে কিনা তা পরীক্ষা করা
      - name: Check if changes are only in the 'blogs' folder
        run: |
          echo "Files changed in this PR:"
          echo "${{ steps.changed-files.outputs.changed_files }}"
          
          # প্রতিটি পরিবর্তিত ফাইল পরীক্ষা করা হচ্ছে
          for file in ${{ steps.changed-files.outputs.changed_files }}; do
            # যদি কোনো ফাইল 'blogs/' ফোল্ডারের বাইরে থাকে
            if [[ ! "$file" == blogs/* ]]; then
              echo "❌ ERROR: Changes outside the 'blogs' folder are not allowed."
              echo "File '$file' is not in the allowed folder."
              # একটি এরর কোড দিয়ে প্রসেস বন্ধ করা হচ্ছে, যা Action-টিকে Fail করে দেবে
              exit 1
            fi
          done
          
          echo "✅ SUCCESS: All changes are within the 'blogs' folder."

